# Generated by Django 6.0.4 on 2026-04-30 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("weight_kg", models.FloatField()),
                ("height_cm", models.FloatField()),
                ("systolic_bp", models.IntegerField(help_text="e.g. 120")),
                ("diastolic_bp", models.IntegerField(help_text="e.g. 80")),
                ("blood_sugar", models.FloatField(help_text="mg/dL fasting")),
                ("cholesterol", models.FloatField(help_text="mg/dL total")),
                ("smoker", models.BooleanField(default=False)),
                ("diabetic", models.BooleanField(default=False)),
                ("risk_score", models.FloatField(blank=True, null=True)),
                ("risk_label", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
